### ISSUE TITLE
fusion process

### ISSUE THREAD

**Issue by BoYangXDU** [EtPan/MSF-Diff#1]
Hi, erting, it's a great work and a really interesting idea！
And I'm curious about the fusion process of your CVPR 2024 work (not release the code, similar to this one) about how to generate **one** synthesis abundance map with **two input** abundance maps (HSI and RGB).
 If it is possible, please tell me the workflow.
 Great thanks. :)

**Comment by EtPan** [comment]
Thank you for your attention and interest! 

After unmixing, we can acquire abundance maps from HSI and RGB. Notably, due to the assumption of sharing endmembers, these abundance maps from these two different sources hold the same shape, which means there is a common low-dimensional abundance space for fusing these multi-source data. Hence, during the training of the generative models, we input all these abundance maps (from HSI and RGB) together. Subsequently, we generate a series of synthetic abundance maps using the trained generative AI models. 

I hope this clarifies the workflow for you. The code of UBF (CVPR 2024) will be released soon. If you have any further questions or need more details, feel free to ask!

**Comment by EtPan** [comment]
Thanks for your attention and interest! 

After unmixing, we can acquire abundance maps from HSI and RGB. Notably, due to the assumption of sharing endmembers, these abundance maps from these two different sources hold the same shape, which means there is a common low-dimensional abundance space for fusing these multi-source data. Hence, during the training of the generative models, we simply input all these abundance maps together. Subsequently, we generate a series of synthetic abundance maps using the trained generative AI models. 

I hope this clarifies the workflow for you. The code of UBF (CVPR 2024) will be released soon. If you have any further questions or need more details, feel free to ask!

**Comment by BoYangXDU** [comment]
Thanks erting, it helps a lot.
Great thanks.
